version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:13
    container_name: garant_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garant
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - garant-network
    restart: unless-stopped

  # Kafka for event streaming
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: garant_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - garant-network
    healthcheck:
      test: ["CMD-SHELL", "echo srvr | nc localhost 2181 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: garant_kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 1000
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_COMPRESSION_TYPE: 'gzip'
    networks:
      - garant-network
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc zookeeper 2181"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped

  # NestJS application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: garant_app
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "4200:4200"
      - "50060:50051"
      - "50061:50053"
      - "50062:50054"
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - garant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4200/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - NODE_ENV=development
      - PORT=4200
      - GRPC_URL=0.0.0.0:50060
      - DEALS_SERVICE_URL=0.0.0.0:50061
      - DISPUTES_SERVICE_URL=0.0.0.0:50062
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/garant?schema=public
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=your-strong-secret-key
      - SENTRY_DSN=https://1b7008922ee3c967cfb9c896bc345c35@o4504702503682048.ingest.us.sentry.io/4509094808256512
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    # Uncomment the line below if you want to override the entrypoint
    # command: ["npm", "run", "dev"]

networks:
  garant-network:
    driver: bridge

volumes:
  postgres_data:










# services:
#   deal-service:
#     build: .
#     ports:
#       - "3000:3000"  # HTTP
#       - "50051:50051" # gRPC
#       - "3001:3001"  # WebSocket
#     environment:
#       - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/deal-service
#       - KAFKA_BROKER=kafka:9092
#       - JWT_SECRET=${JWT_SECRET}
#     depends_on:
#       - postgres
#       - kafka

#   postgres:
#     image: postgres:15
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=deal-service
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   zookeeper:
#     image: confluentinc/cp-zookeeper:7.4.0
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181

#   kafka:
#     image: confluentinc/cp-kafka:7.4.0
#     depends_on:
#       - zookeeper
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#       KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

# volumes:
#   postgres_data: