#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running post-merge hooks..."

# Проверка, изменился ли package.json
if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep --quiet "package.json"; then
  echo "package.json has changed. Installing dependencies..."
  npm install
fi

# Проверка, изменился ли prisma/schema.prisma
if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep --quiet "prisma/schema.prisma"; then
  echo "Prisma schema has changed. Generating Prisma client..."
  npm run db-generate
fi

# Проверка, изменились ли proto файлы
if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep --quiet "src/proto/.*\.proto$"; then
  echo "Proto files have changed. Generating proto files..."
  npm run proto:gen
fi 